Added backup files explorer

diff --git a/pkgs/curios-manager/bin/curios-manager b/pkgs/curios-manager/bin/curios-manager
--- a/pkgs/curios-manager/bin/curios-manager
+++ b/pkgs/curios-manager/bin/curios-manager
@@ -101,6 +101,10 @@ if ! available fwupdmgr; then
   echo -e "${RED}fwupdmgr command not found!${NC}"
   exit 2
 fi
+if ! available ncdu; then
+  echo -e "${RED}ncdu command not found!${NC}"
+  exit 2
+fi
 # Get current OS version
 if [ ! -f /etc/os-release ]; then
   echo -e "${RED}/etc/os-release file not found!${NC}"
