Base for nix search package.

diff --git a/pkgs/curios-manager/bin/curios-manager b/pkgs/curios-manager/bin/curios-manager
--- a/pkgs/curios-manager/bin/curios-manager
+++ b/pkgs/curios-manager/bin/curios-manager
@@ -105,6 +105,10 @@ if ! available ncdu; then
   echo -e "${RED}ncdu command not found!${NC}"
   exit 2
 fi
+if ! available nix-search; then
+  echo -e "${RED}nix-search command not found!${NC}"
+  exit 2
+fi
 # Get current OS version
 if [ ! -f /etc/os-release ]; then
   echo -e "${RED}/etc/os-release file not found!${NC}"
