Release 0.14 - changed reboot after upgrade logic.

diff --git a/pkgs/curios-manager/bin/curios-update b/pkgs/curios-manager/bin/curios-update
--- a/pkgs/curios-manager/bin/curios-update
+++ b/pkgs/curios-manager/bin/curios-update
@@ -51,7 +51,7 @@ ${GREY}EXAMPLES:${NC}
 }
 
 #------------- var init state
-readonly SCRIPT_VERSION="0.9";
+readonly SCRIPT_VERSION="0.10";
 VERBOSE=0;
 CHECK_ONLINE=0;
 UPGRADE_SYSTEM=0;
@@ -116,15 +116,27 @@ available() { command -v "$1" >/dev/null; }
 
 if ! available notify-send; then
   echo -e "${RED}notify-send command not found!${NC}"
-  exit 2
+  exit 1
 fi
 if ! available wget; then
   echo -e "${RED}wget command not found!${NC}"
-  exit 2
+  exit 1
 fi
 if ! available curl; then
   echo -e "${RED}curl command not found!${NC}"
-  exit 2
+  exit 1
+fi
+if ! available wget; then
+  echo -e "${RED}wget command not found!${NC}"
+  exit 1
+fi
+if ! available jq; then
+  echo -e "${RED}jq command not found!${NC}"
+  exit 1
+fi
+if ! available tar; then
+  echo -e "${RED}tar command not found!${NC}"
+  exit 1
 fi
 
 # check online latest version
@@ -156,6 +168,7 @@ upgrade_curios() {
   install -D -m 644 -t /etc/nixos/ "$extracted_source_path"/configuration.nix
   if [ ! -f /etc/nixos/settings.nix ]; then
     install -D -m 644 -t /etc/nixos/ "$extracted_source_path"/settings.nix
+    echo -e "${YELLOW}Default settings.nix file installed!${NC} Edit /etc/nixos/settings.nix to match your username."
   fi
   if [ ! -f "$extracted_source_path"/logo.txt ]; then
     install -D -m 644 -t /etc/nixos/ "$extracted_source_path"/logo.txt
@@ -171,7 +184,7 @@ upgrade_curios() {
     echo -e "${RED}Nix channel not found in configuration.nix!${NC}"
     exit 1
   fi
-  if sudo nix-channel --list | grep -q "$NIX_CHANNEL_URL"; then
+  if nix-channel --list | grep -q "$NIX_CHANNEL_URL"; then
     echo -e "${BLUE}Nix channel is already up-to-date.${NC}"
   else
     echo -e "${YELLOW}Updating Nix channel...${NC}"
@@ -216,4 +229,5 @@ fi
 
 if [ $UPGRADABLE -eq 1 ] && [ $UPGRADE_SYSTEM -eq 1 ]; then
   upgrade_curios
+  exit 2
 fi
